### ISSUE TITLE
Plugin can't write to temp folder

### ISSUE THREAD

**Issue by sgarton** [shsteimer/IntelliVault#1]
com.intellij.openapi.application.Application.runWriteAction(Lcom/intellij/openapi/util/ThrowableComputable;)Ljava/lang/Object;: com.intellij.openapi.application.Application.runWriteAction(Lcom/intellij/openapi/util/ThrowableComputable;)Ljava/lang/Object;
java.lang.NoSuchMethodError: com.intellij.openapi.application.Application.runWriteAction(Lcom/intellij/openapi/util/ThrowableComputable;)Ljava/lang/Object;
    at com.crownpartners.intellivault.utils.FileUtils.copyFileContents(FileUtils.java:234)
    at com.crownpartners.intellivault.utils.FileUtils.copyFile(FileUtils.java:226)
    at com.crownpartners.intellivault.utils.FileUtils.copyExportContents(FileUtils.java:204)
    at com.crownpartners.intellivault.utils.FileUtils.copyExportContents(FileUtils.java:139)
    at com.crownpartners.intellivault.services.impl.IntelliVaultServiceImpl$2.run(IntelliVaultServiceImpl.java:109)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:162)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:333)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:420)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by shsteimer** [comment]
Can you provide a bit more context.

Version of The plugin you are running?
Version on IntelliJ you are running?  Community or Ultmate?
OS?
Version of Vault you are using with IntelliVault?
Version of CQ you are trying to operate against?
What were you trying to do when this happened, Import or Export?
